CREATE TABLE sub_centers (
    sub_center_id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    block_id INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    CONSTRAINT fk_subcenter_block 
        FOREIGN KEY (block_id) REFERENCES blocks(block_id)
        ON DELETE CASCADE
);
